---
baseURL: https://0x1.im
disablePathToLower: true
languageCode: zh-hans
hasCJKLanguage: true
title: Scholer's Pages
pygmentsCodefences: true
pygmentsUseClasses: true
publishDir: docs
disableKinds:
  - RSS
  - sitemap
taxonomies:
  tag: tags
# theme: hello-friend-ng

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  homeSubtitle: 深漂码农，主要从事 PHP/Golang 应用开发，兴趣爱好广泛。
  defaultTheme: dark
  logo:
    logoText: "echo 0x1.im"
  social:
    - name: github
      url: 'https://github.com/'

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 10
    - name: Tags
      url: /tags/
      weight: 20
    - name: About
      url: /about/
      weight: 30
